[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nsflows"
version = "0.1.0"
description = "Generative nested sampling of atomistic thermodynamic landscapes with normalizing flows"
authors = [
    {name = "Alessandro Coretti"},
    {name = "Nico Unglert"},
]
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.4",
    "scipy==1.12.0",
    "torch==2.2.1",
    "matplotlib==3.8.0",
    "einops==0.7.0",
    "tqdm==4.67.1",
]

[project.optional-dependencies]
numexp = [
    "bilby==2.8.0",
    "lalsuite==7.26.13",
]

[tool.setuptools.packages.find]
where = ["."]
